import Api from './api';

/**
 * Phase 8.0 — Portfolio Operations API
 *
 * All execute requests use only previewId + Idempotency-Key.
 * No action IDs or payload are sent on execute — the server loads the
 * operation from the stored preview record.
 */

export const PortfolioOperationsApi = {

  /**
   * POST /api/portfolio/operations/preview
   * @param {object} params - { operation, mode, actionIds, payload }
   */
  async previewBulkOperation({ operation, mode, actionIds, payload }) {
    return Api.post('/api/portfolio/operations/preview', {
      operation,
      mode,
      actionIds,
      payload,
    });
  },

  /**
   * POST /api/portfolio/operations/:previewId/execute
   * Sends ONLY the previewId (in URL) and Idempotency-Key (in header).
   * No action IDs or payload in the body.
   * @param {string} previewId       - UUID from preview response
   * @param {string} idempotencyKey  - UUID v4 generated by caller
   */
  async executeBulkOperation(previewId, idempotencyKey) {
    const token = Api.getToken();
    const headers = {
      'Content-Type': 'application/json',
      'Idempotency-Key': idempotencyKey,
    };
    if (token) headers['Authorization'] = `Bearer ${token}`;

    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 30000);

    let res;
    try {
      res = await fetch(`/api/portfolio/operations/${encodeURIComponent(previewId)}/execute`, {
        method: 'POST',
        headers,
        signal: controller.signal,
      });
    } catch (fetchErr) {
      clearTimeout(timer);
      if (fetchErr.name === 'AbortError') {
        throw new Error('Request timed out. Please check your network or try again.');
      }
      throw fetchErr;
    }
    clearTimeout(timer);

    if (!res.ok) {
      let errorMessage = `Execute failed (${res.status} ${res.statusText || ''})`.trim();
      let errorData = null;
      try {
        const text = await res.text();
        try {
          errorData = JSON.parse(text);
          if (errorData && (errorData.error || errorData.message)) {
            errorMessage = errorData.error || errorData.message;
          }
        } catch {
          if (text && text.trim().length > 0 && text.trim().length < 400) {
            errorMessage = text.trim();
          }
        }
      } catch {}

      const err = new Error(errorMessage);
      err.status = res.status;
      err.code = errorData && errorData.code;
      err.data = errorData;
      throw err;
    }

    const contentType = res.headers.get('content-type') || '';
    const data = contentType.includes('application/json') ? await res.json() : await res.blob();
    return data;
  },

  /**
   * GET /api/portfolio/operations/history
   * @param {object} params - { page, limit }
   */
  async getBatchHistory({ page = 1, limit = 20 } = {}) {
    const qs = new URLSearchParams({ page, limit }).toString();
    return Api.get(`/api/portfolio/operations/history?${qs}`);
  },

  /**
   * GET /api/portfolio/operations/pending-approvals
   * @param {object} params - { page, limit }
   */
  async getPendingApprovals({ page = 1, limit = 20 } = {}) {
    const qs = new URLSearchParams({ page, limit }).toString();
    return Api.get(`/api/portfolio/operations/pending-approvals?${qs}`);
  },

  /**
   * POST /api/portfolio/operations/:batchId/approve
   * @param {string} batchId
   * @param {string} comments
   */
  async approveBatch(batchId, comments = '') {
    return Api.post(`/api/portfolio/operations/${encodeURIComponent(batchId)}/approve`, { comments });
  },

  /**
   * POST /api/portfolio/operations/:batchId/reject
   * @param {string} batchId
   * @param {string} reason
   */
  async rejectBatch(batchId, reason) {
    return Api.post(`/api/portfolio/operations/${encodeURIComponent(batchId)}/reject`, { reason });
  },
};

export default PortfolioOperationsApi;
